<div class="col-main">
	<div class="my-account">
		<div class="page-title">
			<h1><?php echo Mage::helper('client')->__('Your request has been received'); ?></h1>
		</div>

		<div class="fieldset">
			<h2 class="legend">General Information</h2>
			<ul class="form-list">
				<li class="control">
					<label><?php echo Mage::helper('client')->__('Ticket ID'); ?></label>
					<label><?php echo $this->ticketMaskID; ?></label>
				</li>
			</ul>
		</div>
	</div>
</div>