<?php $ticketDetails = $this->getData('ticketDetails'); ?>

<div class="col-main">
	<div class="my-account">
		<div class="page-title">
			<h1><?php echo Mage::helper('client')->__('Your request has been received') ?></h1>
		</div>
		<div><?php echo Mage::helper('client')->__('We have received your request and will get back to you with further details shortly.') ?></div>

		<div class="fieldset">
			<h2 class="legend">General Information</h2>
			<ul class="form-list">
				<li class="control">
					<label><?php echo Mage::helper('client')->__('Ticket ID'); ?>:</label>&nbsp;&nbsp;
					<?php echo $this->getData('ticketMaskID'); ?>
				</li>
				<li class="control">
					<label><?php echo Mage::helper('client')->__('Full Name'); ?>:</label>&nbsp;&nbsp;
					<?php echo $ticketDetails['ticketfullname']; ?>
				</li>
				<li class="control">
					<label><?php echo Mage::helper('client')->__('Email'); ?>:</label>&nbsp;&nbsp;
					<?php echo $ticketDetails['ticketemail']; ?>
				</li>
			</ul>
		</div>

		<div class="fieldset">
			<h2 class="legend"><?php echo Mage::helper('client')->__('Subject') ?> :  <?php echo $ticketDetails['ticketsubject']; ?></h2>
			<ul class="form-list">
				<li class="control">
					<?php echo $ticketDetails['ticketmessage']; ?>
				</li>
			</ul>
		</div>
	</div>
</div>