<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php $collection = $this->getCollection(); ?>
	<div class="page-title">
		<h1><?php echo $this->__('View Tickets') ?></h1>
	</div>
<?php echo $this->getToolbarHtml(); ?>
<?php if ($collection->getSize()): ?>
	<table class="data-table" id="tickets-table">
		<col width="1"/>
		<col width="1"/>
		<col width="1"/>
		<col width="1"/>
		<col width="1"/>
		<col width="1"/>
		<thead>
		<tr>
			<th><?php echo $this->__('Ticket ID') ?></th>
			<th><?php echo $this->__('Last Update') ?></th>
			<th><?php echo $this->__('Last Replier') ?></th>
			<th><?php echo $this->__('Department') ?></th>
			<th><?php echo $this->__('Type') ?></th>
			<th><?php echo $this->__('Priority') ?></th>

		</tr>
		</thead>
		<tbody>
		<?php foreach ($collection as $_obj): ?>
			<tr>
				<td colspan="6"><a href="<?php echo Mage::getUrl('*/*/viewTicketDetails', array('tid' => $_obj->ticketid)); ?>"
								   style="text-decoration: none;"><?php echo $_obj->subject; ?></a></td>
			</tr>
			<tr>
				<td><?php echo $_obj->displayticketid; ?></td>
				<td><span class="nobr"><?php echo $_obj->lastactivity; ?></span></td>
				<td><?php echo $_obj->lastreplier; ?></td>
				<td><?php echo $_obj->department; ?></td>
				<td><?php echo $_obj->type; ?></td>
				<td><?php echo $_obj->priority; ?></td>
			</tr>
		<?php endforeach; ?>
		</tbody>
	</table>
	<script type="text/javascript">decorateTable('tickets-table');</script>
<?php else: ?>
	<p><?php echo $this->__('The collection is empty.'); ?></p>
<?php endif ?>